import {
  Activity,
  ArrowRight,
  Award,
  Banknote,
  BarChart3,
  Building2,
  CheckCircle,
  Clock,
  Code,
  CreditCard,
  Database,
  Eye,
  FileText,
  Fingerprint,
  Gamepad2,
  Gift,
  Globe,
  Headphones,
  History,
  IdCard,
  Key,
  Landmark,
  Layers,
  Lock,
  MessageSquare,
  Package,
  Percent,
  RefreshCw,
  Send,
  Server,
  Settings,
  ShieldCheck,
  Smartphone,
  Star,
  Target,
  Ticket,
  TrendingUp,
  Users,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-right": ArrowRight,
  award: Award,
  banknote: Banknote,
  "bar-chart-3": BarChart3,
  "building-2": Building2,
  "check-circle": CheckCircle,
  clock: Clock,
  code: Code,
  "credit-card": CreditCard,
  database: Database,
  eye: Eye,
  "file-text": FileText,
  fingerprint: Fingerprint,
  "gamepad-2": Gamepad2,
  gift: Gift,
  globe: Globe,
  headphones: Headphones,
  history: History,
  "id-card": IdCard,
  key: Key,
  landmark: Landmark,
  layers: Layers,
  lock: Lock,
  "message-square": MessageSquare,
  package: Package,
  percent: Percent,
  "refresh-cw": RefreshCw,
  send: Send,
  server: Server,
  settings: Settings,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  star: Star,
  target: Target,
  ticket: Ticket,
  "trending-up": TrendingUp,
  users: Users,
  wallet: Wallet,
  zap: Zap,
};

interface IconResolverProps {
  name: string;
  size?: number;
  className?: string;
}

export function IconResolver({
  name,
  size = 24,
  className,
}: IconResolverProps) {
  const Icon = iconMap[name];
  if (!Icon) return null;
  return <Icon size={size} className={className} />;
}
